version: 2

sources:
  - name: staging
    database: "{{ env_var('DBT_DATABASE', 'kestra-sandbox-450921') }}"
    schema: "{{ env_var('DBT_SCHEMA', 'de_zoomcamp') }}"
      # loaded_at_field: record_loaded_at
    tables:
      - name: green_tripdata
      - name: yellow_tripdata
         # freshness:
           # error_after: {count: 6, period: hour}